#!/bin/bash -l
#$ -P batmanlab
#$ -cwd
#$ -j y
#$ -N cxrclip_lp
#$ -l h_rt=24:00:00
#$ -l mem_free=24G
#$ -l gpus=1
#$ -pe omp 8
#$ -o /restricted/projectnb/batmanlab/ahcmwong/outputs/classification/linear_probe/cxr_clip/ResNet50-M/logs

export OMP_NUM_THREADS=$NSLOTS

module load cuda/12.8

# activate your venv
source /restricted/projectnb/batmanlab/ahcmwong/CXRBench/cxrclip-env/bin/activate

# Go to project dir (so relative paths in config work)
cd /restricted/projectnb/batmanlab/ahcmwong/CXRBench

# 4) Run training
python tasks/classification/linear_probing/MIMIC-CXR/CXR-CLIP/train.py \
  --config tasks/classification/linear_probing/MIMIC-CXR/CXR-CLIP/config.yaml
