#!/bin/bash
#$ -P batmanlab
#$ -cwd
#$ -j y
#$ -N cxrclip_lp
#$ -l h_rt=24:00:00
#$ -l mem_free=24G
#$ -l gpus=1
#$ -o /restricted/projectnb/batmanlab/ahcmwong/outputs/classification/linear_probe/cxr_clip/ResNet50-M/logs

# Activate env
source /restricted/projectnb/batmanlab/ahcmwong/CXRBench/cxrclip-env/bin/activate

# Run training
python /restricted/projectnb/batmanlab/ahcmwong/CXRBench/tasks/classification/linear_probing/MIMIC-CXR/CXR-CLIP/train.py \
  --config /restricted/projectnb/batmanlab/ahcmwong/CXRBench/tasks/classification/linear_probing/MIMIC-CXR/CXR-CLIP/config.yaml
